INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P001', true, 'Fone de Ouvido Bluetooth', 149.90, 50);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P002', true, 'Smartphone Android 128GB', 1299.00, 20);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P003', true, 'Notebook 15.6" i5 8GB RAM', 2899.99, 15);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P004', true, 'Monitor LED 24"', 799.00, 30);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P005', true, 'Teclado Mecânico RGB', 349.50, 40);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P006', true, 'Mouse Gamer 16000 DPI', 179.90, 60);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P007', true, 'HD Externo 1TB', 299.00, 25);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P008', true, 'SSD 480GB', 229.99, 70);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P009', true, 'Câmera Web Full HD', 199.90, 45);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P010', true, 'Impressora Multifuncional Wi-Fi', 499.90, 12);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P011', true, 'Carregador Portátil 10000mAh', 99.90, 80);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P012', true, 'Smartwatch Pulseira Silicone', 299.00, 30);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P013', true, 'Caixa de Som Bluetooth', 189.90, 50);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P014', true, 'Pen Drive 64GB', 49.90, 100);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P015', true, 'Cabo USB-C Reforçado', 29.90, 150);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P016', true, 'Adaptador HDMI para VGA', 39.90, 60);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P017', true, 'Roteador Wi-Fi 1200Mbps', 259.00, 22);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P018', true, 'Estabilizador 500VA', 199.00, 18);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P019', true, 'Controle Sem Fio para PC', 149.00, 35);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P020', true, 'Hub USB 3.0 4 Portas', 89.90, 45);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P021', true, 'Tripé com Suporte Celular', 69.90, 75);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P022', true, 'Lâmpada Inteligente Wi-Fi', 59.90, 85);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P023', true, 'Suporte Articulado Monitor', 129.00, 27);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P024', true, 'Fonte ATX 500W', 249.00, 13);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P025', true, 'Cooler para Notebook', 109.90, 38);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P026', true, 'Microfone Condensador USB', 229.90, 19);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P027', true, 'Controle Universal Smart TV', 59.00, 66);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P028', true, 'Repetidor de Sinal Wi-Fi', 119.00, 23);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P029', true, 'Webcam 4K com Microfone', 349.00, 9);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P030', true, 'Placa de Vídeo 4GB DDR6', 1349.00, 7);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P031', true, 'Bateria Portátil 20000mAh', 139.90, 33);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P032', true, 'Projetor Portátil LED', 899.00, 11);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P033', true, 'Tablet Android 10" 64GB', 1149.00, 14);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P034', true, 'Leitor de Cartões SD/USB', 39.90, 88);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P035', true, 'HDMI Switch 3 Entradas', 79.90, 21);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P036', true, 'Conversor Digital Full HD', 129.00, 17);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P037', true, 'Extensão Elétrica 5 Tomadas', 54.90, 72);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P038', true, 'Filtro de Linha 6 Tomadas', 69.00, 59);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P039', true, 'Cabo de Rede CAT6 10m', 45.90, 64);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P040', true, 'Placa Mãe AM4 DDR4', 679.00, 8);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P041', true, 'Memória RAM 8GB DDR4', 299.00, 29);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P042', true, 'Processador Ryzen 5 5600G', 1099.00, 6);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P043', true, 'Placa de Som USB Externa', 79.90, 43);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P044', true, 'Notebook Gamer 16GB 512GB', 5299.00, 4);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P045', true, 'Monitor Curvo 27" Gamer', 1699.00, 10);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P046', true, 'Dock Station USB-C', 259.90, 16);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P047', true, 'Mousepad Gamer XL RGB', 119.00, 39);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P048', true, 'Câmera de Segurança IP', 349.90, 13);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P049', true, 'Echo Dot Smart Speaker', 379.00, 22);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P050', true, 'Sensor de Presença Wi-Fi', 89.00, 44);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P051', true, 'Antena Digital Externa', 129.90, 18);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P052', true, 'Raspberry Pi 4 4GB RAM', 499.90, 10);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P053', true, 'Teclado Wireless com Touch', 159.90, 26);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P054', true, 'Tablet Infantil 7" Wi-Fi', 449.00, 20);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P055', true, 'Balança Digital Inteligente', 219.00, 15);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P056', true, 'Carregador Turbo 3.0', 89.00, 70);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P057', true, 'Luminária LED com USB', 99.00, 38);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P058', true, 'Chave HDMI Manual 3x1', 59.90, 24);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P059', true, 'Relógio Digital com Alexa', 419.00, 12);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P060', true, 'Carregador sem fio 15W', 129.90, 32);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P061', true, 'Fita LED Inteligente RGB', 169.90, 21);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P062', true, 'Aspirador Robô Automático', 1499.00, 6);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P063', true, 'Smartband com Monitor Cardíaco', 199.00, 28);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P064', true, 'Receptor Bluetooth P2', 49.00, 47);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P065', true, 'Placa Arduino UNO R3', 99.90, 50);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P066', true, 'Kit Eletrônica Iniciante', 159.90, 19);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P067', true, 'Interruptor Wi-Fi Inteligente', 79.00, 33);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P068', true, 'Sensor de Temperatura IoT', 89.90, 25);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P069', true, 'Câmera Ação Full HD', 249.90, 17);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P070', true, 'Power Bank com Painel Solar', 199.00, 31);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P071', true, 'Case Raspberry Pi com Cooler', 59.90, 43);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P072', true, 'Display LCD 16x2 I2C', 49.90, 67);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P073', true, 'Controle PS4 Original', 349.00, 14);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P074', true, 'Controle Xbox Series', 399.00, 10);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P075', true, 'Headset Gamer 7.1', 289.90, 23);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P076', true, 'Suporte PS5 Vertical', 89.00, 35);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P077', true, 'Ventoinha RGB 120mm', 79.90, 40);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P078', true, 'Fonte Modular 650W 80Plus', 529.00, 8);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P079', true, 'Cooler Water Cooler 240mm', 699.00, 5);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P080', true, 'Painel Solar 50W', 899.00, 3);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P081', true, 'Inversor Solar 12V 600W', 1199.00, 4);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P082', true, 'Bateria Estacionária 150Ah', 1899.00, 2);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P083', true, 'Multímetro Digital Profissional', 229.90, 14);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P084', true, 'Osciloscópio Portátil', 1399.00, 1);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P085', true, 'Anemômetro Digital USB', 319.90, 9);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P086', true, 'Sensor de Gás Wi-Fi', 129.00, 18);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P087', true, 'Relé Wi-Fi Automação', 89.00, 25);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P088', true, 'Disco Rígido 2TB SATA', 399.00, 15);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P089', true, 'SSD NVMe 1TB', 599.00, 11);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P090', true, 'Teclado Gamer Semi Mecânico', 199.00, 28);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P091', true, 'Switch Gigabit 8 Portas', 259.00, 7);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P092', true, 'Smart TV 43" 4K', 1899.00, 6);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P093', true, 'TV Box Android 4GB RAM', 299.00, 16);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P094', true, 'Mini Teclado Wireless', 119.00, 22);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P095', true, 'Joystick Arcade USB', 189.00, 19);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P096', true, 'Lente Clip para Celular', 39.90, 48);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P097', true, 'Suporte Veicular Magnético', 49.90, 51);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P098', true, 'Teclado numérico USB', 59.90, 37);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P099', true, 'Pen Drive 128GB', 89.90, 55);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P100', true, 'Cabo Lightning Original', 129.00, 42);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P101', true, 'Relógio Inteligente Redondo', 349.00, 18);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P102', true, 'Controle RGB Endereçável', 109.00, 27);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P103', true, 'Cabo HDMI 4K 2m', 34.90, 66);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P104', true, 'Câmera 360º IP', 499.90, 13);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P105', true, 'Cadeira Gamer Reclinável', 1299.00, 5);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P106', true, 'Base Refrigerada RGB', 189.00, 20);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P107', true, 'Filtro de Linha Inteligente', 149.00, 17);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P108', true, 'Ventilador USB Portátil', 39.90, 53);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P109', true, 'Caixa de Som com Alexa', 429.00, 8);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P110', true, 'Organizador Cabos Silicone', 29.90, 120);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P111', true, 'Relógio com Projetor', 99.00, 36);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P112', true, 'Mouse Ergonômico Vertical', 129.00, 29);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P113', true, 'Kit Chave Torx Eletrônica', 89.90, 41);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P114', true, 'Testador de Cabos RJ45', 59.90, 35);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P115', true, 'Alto-Falante Portátil USB', 79.90, 38);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P116', true, 'HD Notebook 500GB', 199.00, 24);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P117', true, 'Suporte Celular Mesa', 49.00, 70);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P118', true, 'Controle Ar Condicionado Universal', 69.90, 33);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P119', true, 'HDMI Extender via Ethernet', 149.00, 12);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P120', true, 'Carregador Carro 2 USB', 39.90, 85);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P121', true, 'Powerline Internet 500Mbps', 279.00, 7);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P122', true, 'Mini Switch 5 Portas', 99.00, 31);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P123', true, 'Scanner de Documentos', 799.00, 6);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P124', true, 'Microfone Lapela USB-C', 89.00, 25);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P125', true, 'HD Externo 2TB', 499.00, 9);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P126', true, 'Tablet com Teclado', 1399.00, 14);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P127', true, 'Kit Raspberry Completo', 699.00, 10);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P128', true, 'Arduino Mega 2560', 179.90, 13);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P129', true, 'Fita LED USB 5V', 39.00, 60);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P130', true, 'Chave de Fenda Elétrica', 199.00, 21);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P131', true, 'Estação de Solda Digital', 299.00, 16);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P132', true, 'Balança Cozinha Digital', 59.00, 34);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P133', true, 'Despertador com Rádio', 79.00, 27);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P134', true, 'Campainha Wi-Fi Vídeo', 499.00, 8);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P135', true, 'Lixeira com Sensor Automático', 299.00, 11);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P136', true, 'Cabo Óptico de Áudio', 49.90, 45);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P137', true, 'Joystick Bluetooth Android', 149.00, 30);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P138', true, 'Termômetro Digital Infravermelho', 179.00, 18);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P139', true, 'Estabilizador Tensão Inteligente', 319.00, 5);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P140', true, 'Sensor Magnético Portas IoT', 59.00, 23);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P141', true, 'Fonte Universal Notebook', 179.90, 12);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P142', true, 'Câmera Baby Monitor Wi-Fi', 329.90, 9);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P143', true, 'Organizador Cabos Magnético', 29.00, 90);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P144', true, 'Espelho com LED USB', 119.00, 15);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P145', true, 'Cortina Automatizada Wi-Fi', 649.00, 2);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P146', true, 'Suporte Notebook Regulável', 159.00, 19);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P147', true, 'Controle DVR CFTV USB', 69.90, 10);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P148', true, 'Sensor de Umidade IoT', 79.90, 7);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P149', true, 'Chave Liga/Desliga 110v Wi-Fi', 89.90, 14);
INSERT INTO tbl_produtos (sku, ativo, descricao, preco, quantidade) VALUES ('P150', true, 'Switch HDMI Automático', 109.90, 21);